### ISSUE TITLE
Error type in ZIO wrappers for LWJGL

### ISSUE THREAD

**Issue by bbarker** [wongelz/zio3d#3]
I noticed that most of the functions in e.g. `glfw\package.scala` have a return type like `UIO[A]` or ` ZIO[GLFW, Nothing, A]`, implying that exceptions should not be possible. However, it seems that it like is possible - here's a case for `NullPointerException`:

https://linustechtips.com/topic/584923-java-lwjgl-3-exception/?tab=comments

My understanding is that it may be more accurate to model these with the `Throwable` error type, e.g. `Task[A]` or `RIO[GLFW, A]`, though there may be downsides to this I'm not aware of (likely related to needing to handle that rather ambiguous error type).

**Comment by wongelz** [comment]
@bbarker ZIO's error channel is for _recoverable_ errors though - I think if LWJGL's runtime checks throw an exception then it is a code defect (hopefully only observed during development) and is thus _unrecoverable_ and we should let it crash. And if we ignore the runtime checks (it's possible to disable them) and treat LWJGL as a native wrapper - that native code cannot throw exceptions anyway (since it's not java code).

**Comment by bbarker** [comment]
@wongelz ah I see, thanks for the explanation - makes sense!
